In [95]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
!pip install xgboost

In [96]:
test = pd.read_csv("D://M_AI//Machine Learning//Projects//Mercedes//test.csv")
train = pd.read_csv("D://M_AI//Machine Learning//Projects//Mercedes//train.csv")

In [97]:
#Checking for null values in test data
test.isnull().sum()

ID      0
X0      0
X1      0
X2      0
X3      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 377, dtype: int64

In [98]:
#Checking for null values in test data
train.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [99]:
## CHECKING THE UNIQUE VALUES
# number of unique attributes in each columns of test data
for i in test.columns:
    print(test[i].unique(),"\t",test[i].nunique())
    

[   1    2    3 ... 8413 8414 8416] 	 4209
['az' 't' 'w' 'y' 'x' 'f' 'ap' 'o' 'ay' 'al' 'h' 'z' 'aj' 'd' 'v' 'ak'
 'ba' 'n' 'j' 's' 'af' 'ax' 'at' 'aq' 'av' 'm' 'k' 'a' 'e' 'ai' 'i' 'ag'
 'b' 'am' 'aw' 'as' 'r' 'ao' 'u' 'l' 'c' 'ad' 'au' 'bc' 'g' 'an' 'ae' 'p'
 'bb'] 	 49
['v' 'b' 'l' 's' 'aa' 'r' 'a' 'i' 'p' 'c' 'o' 'm' 'z' 'e' 'h' 'w' 'g' 'k'
 'y' 't' 'u' 'd' 'j' 'q' 'n' 'f' 'ab'] 	 27
['n' 'ai' 'as' 'ae' 's' 'b' 'e' 'ak' 'm' 'a' 'aq' 'ag' 'r' 'k' 'aj' 'ay'
 'ao' 'an' 'ac' 'af' 'ax' 'h' 'i' 'f' 'ap' 'p' 'au' 't' 'z' 'y' 'aw' 'd'
 'at' 'g' 'am' 'j' 'x' 'ab' 'w' 'q' 'ah' 'ad' 'al' 'av' 'u'] 	 45
['f' 'a' 'c' 'e' 'd' 'g' 'b'] 	 7
['d' 'b' 'a' 'c'] 	 4
['t' 'b' 'a' 'z' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac'
 'ad' 'ae' 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa'] 	 32
['a' 'g' 'j' 'l' 'i' 'd' 'f' 'h' 'c' 'k' 'e' 'b'] 	 12
['w' 'y' 'j' 'n' 'm' 's' 'a' 'v' 'r' 'o' 't' 'h' 'c' 'k' 'p' 'u' 'd' 'g'
 'b' 'q' 'e' 'l' 'f' 'i' 'x'] 	 25
[0 1] 	 2
[0 1] 	 2
[0 1] 	 2
[0 1

In [100]:
# number of unique attributes in each columns of train data
for i in train.columns:
    print(train[i].unique(),"\t",train[i].nunique())

[   0    6    7 ... 8412 8415 8417] 	 4209
[130.81  88.53  76.26 ...  85.71 108.77  87.48] 	 2545
['k' 'az' 't' 'al' 'o' 'w' 'j' 'h' 's' 'n' 'ay' 'f' 'x' 'y' 'aj' 'ak' 'am'
 'z' 'q' 'at' 'ap' 'v' 'af' 'a' 'e' 'ai' 'd' 'aq' 'c' 'aa' 'ba' 'as' 'i'
 'r' 'b' 'ax' 'bc' 'u' 'ad' 'au' 'm' 'l' 'aw' 'ao' 'ac' 'g' 'ab'] 	 47
['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u' 'p' 'n'
 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab'] 	 27
['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's' 'f' 'd'
 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't' 'an'
 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar'] 	 44
['a' 'e' 'c' 'f' 'd' 'b' 'g'] 	 7
['d' 'b' 'c' 'a'] 	 4
['u' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 'af' 'ag' 'ab' 'ac' 'ad' 'ae'
 'ah' 'l' 'k' 'n' 'm' 'p' 'q' 's' 'r' 'v' 'w' 'o' 'aa'] 	 29
['j' 'l' 'd' 'h' 'i' 'a' 'g' 'c' 'k' 'e' 'f' 'b'] 	 12
['o' 'x' 'e' 'n' 's' 'a' 'h' 'p' 'm' 'k' 'd' 'i' 'v' 'j' 'b' 'q' 'w' 'g'
 'y' 'l' 'f' 'u' 'r' 't' 'c'] 	 25
[0 1] 	 

In [101]:
## CHECKING THE NULL VARIANCES

# find the variances of the group and group the ones greaterthan 0
train_var = train.var()
print(train_var)
train_var1 = pd.DataFrame(train_var)
train_var1.isnull().any()


## Output indicates that there are no variables with zero variance 

ID      5.941936e+06
y       1.607667e+02
X10     1.313092e-02
X11     0.000000e+00
X12     6.945713e-02
            ...     
X380    8.014579e-03
X382    7.546747e-03
X383    1.660732e-03
X384    4.750593e-04
X385    1.423823e-03
Length: 370, dtype: float64


0    False
dtype: bool

In [102]:
## APPLYING LABEL ENCODER
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# assigning labels for different attributes in each columns
for c in train.columns:
    if train[c].dtype == 'object':
         train[c]= le.fit_transform(train[c])
         test[c] = le.fit_transform(test[c])
train.dtypes        

ID        int64
y       float64
X0        int32
X1        int32
X2        int32
         ...   
X380      int64
X382      int64
X383      int64
X384      int64
X385      int64
Length: 378, dtype: object

In [103]:
features = list(set(train.columns)-set(['ID','y']))

X_train = train[features]
y_train = train['y'].values

X_test = test[features]
id_test = train['ID'].values



In [104]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 12)
pca_train = pca.fit_transform(X_train)
pca_test = pca.transform(X_test)

In [105]:
## XGBOOST

import xgboost as xgb

from sklearn.metrics import r2_score

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(pca_train,y_train,test_size=0.2,random_state=42)

d_train = xgb.DMatrix(X_train,label=y_train)
d_valid = xgb.DMatrix(X_valid,label=y_valid)
d_test = xgb.DMatrix(pca_test)

params = {}

params['Objective'] = 'reg:linear'
params['eta'] = 0.02
params['max_depth'] = 4

def xgb_r2score(preds,dtrain):
    labels = dtrain.get_label()
    return 'r2',r2_score(labels,preds)

watchlist = [(d_train,'Train'),(d_valid,'Validation')]

clf = xgb.train(params,d_train,1000,watchlist,early_stopping_rounds=50,
                feval=xgb_r2score,maximize=True,verbose_eval=10)

[06:56:08] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\learner.cc:516: 
Parameters: { Objective } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]	Train-rmse:98.99705	Validation-rmse:98.88675	Train-r2:-59.49743	Validation-r2:-61.82424
Multiple eval metrics have been passed: 'Validation-r2' will be used for early stopping.

Will train until Validation-r2 hasn't improved in 50 rounds.
[10]	Train-rmse:81.14532	Validation-rmse:81.05431	Train-r2:-39.64615	Validation-r2:-41.20883
[20]	Train-rmse:66.60017	Validation-rmse:66.52771	Train-r2:-26.38061	Validation-r2:-27.43520
[30]	Train-rmse:54.76084	Validation-rmse:54.72092	Train-r2:-17.51112	Validation-r2:-18.23791
[40]	Train-rmse:45.14307	Validation-rmse:45.11907	Train-r2:-11.57983	Validation-r2:-12.0789

In [106]:
# PREDICTING Y VALUES
p_test = clf.predict(d_test)
pred = pd.DataFrame()
pred['ID'] = id_test
pred['y'] = p_test
pred.head()

ID           y
0   0   76.945099
1   6   96.783455
2   7   80.978035
3   9   77.336464
4  13  110.291283