In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("D://M_AI//Machine Learning//Demo Datasets//Lesson 10//Recommend.csv")
df.head()

User_ID  Movie_ID  Rating  Timestamp
0      186       302       3  891717742
1       22       377       1  878887116
2      244        51       2  880606923
3      166       346       1  886397596
4      298       474       4  884182806

In [14]:
from sklearn.model_selection import train_test_split
n_users = df.User_ID.unique().shape[0]
n_movies = df.Movie_ID.unique().shape[0]

train_data, test_data = train_test_split(df,test_size=0.25)

In [19]:
# populate the train dataset with random ratings
train_data_matrix = np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1] = line[3]
train_data_matrix    

array([[5., 3., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [21]:
# populate the test dataset with random ratings
test_data_matrix = np.zeros((n_users,n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1] = line[3]
test_data_matrix

array([[0., 0., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
# import library for creating a cosine similarity
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix,metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T,metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]
rating_diff = (train_data_matrix - mean_user_rating)

# perform predictions
user_pred = mean_user_rating + user_similarity.dot(rating_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.64341873,  0.54241045,  0.46964015, ...,  0.28715823,
         0.2871304 ,  0.28713562],
       [ 1.39344821,  0.25612394,  0.14139201, ..., -0.06235125,
        -0.06102791, -0.0607579 ],
       [ 1.39972757,  0.2043923 ,  0.10007126, ..., -0.10938497,
        -0.10772091, -0.10768331],
       ...,
       [ 1.24973133,  0.17382157,  0.06583811, ..., -0.12755475,
        -0.12675332, -0.12651684],
       [ 1.43505209,  0.2609446 ,  0.17056897, ..., -0.03604623,
        -0.03497283, -0.03488965],
       [ 1.48715825,  0.35824769,  0.29544607, ...,  0.11243638,
         0.11240047,  0.11256566]])